#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"
APP_FILE="$REPO_ROOT/nl2sql_app.py"
STREAMLIT_DIR="$REPO_ROOT/.streamlit"
SECRETS_FILE="$STREAMLIT_DIR/secrets.toml"
DEFAULT_DB_NAME="airportdb"

fail() {
  echo "Error: $1" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is not installed or not on PATH."
}

require_command oci

[[ -f "$APP_FILE" ]] || fail "Could not find $APP_FILE"

if [[ ! -f "$HOME/.oci/config" ]]; then
  echo "OCI config not found. Running oci setup config..."
  oci setup config
else
  echo "OCI config already exists at $HOME/.oci/config"
fi

public_key_path=""
if [[ -f "$HOME/.oci/oci_api_key_public.pem" ]]; then
  public_key_path="$HOME/.oci/oci_api_key_public.pem"
elif [[ -d "$HOME/.oci" ]]; then
  public_key_path="$(find "$HOME/.oci" -maxdepth 1 -type f -name '*public*.pem' | head -n 1 || true)"
fi

if [[ -n "${public_key_path:-}" && -f "$public_key_path" ]]; then
  echo
  echo "Public API key detected at: $public_key_path"
  cat "$public_key_path"
else
  echo
  echo "Could not auto-detect a public API key file under $HOME/.oci."
  echo 'If you are still finishing OCI setup, use the public key generated by `oci setup config`.'
fi

read -r -p "Confirm that you have added the public API key to your OCI tenancy console [Y/N]: " usr_conf
case "${usr_conf:-}" in
  Y|y)
    ;;
  *)
    fail "OCI API key confirmation was not received."
    ;;
esac

read -r -p "Enter the OCID of your HeatWave db-system: " hw_ocid
[[ -n "${hw_ocid:-}" ]] || fail "HeatWave OCID is required."

echo "Fetching HeatWave endpoint details..."
ip_address="$(oci mysql db-system get \
  --db-system-id "$hw_ocid" \
  --query 'data.endpoints[0]."ip-address"' \
  --raw-output 2>/dev/null || true)"
port_endpoint="$(oci mysql db-system get \
  --db-system-id "$hw_ocid" \
  --query 'data.endpoints[0].port' \
  --raw-output 2>/dev/null || true)"

[[ -n "$ip_address" ]] || fail "Failed to retrieve the HeatWave IP address."
[[ -n "$port_endpoint" ]] || fail "Failed to retrieve the HeatWave port."

read -r -p "Enter the HeatWave database username: " hw_usr
[[ -n "${hw_usr:-}" ]] || fail "Database username is required."

read -r -s -p "Enter the HeatWave database password: " hw_pswrd
echo
[[ -n "${hw_pswrd:-}" ]] || fail "Database password is required."

read -r -p "Enter the database/schema name [${DEFAULT_DB_NAME}]: " db_name
db_name="${db_name:-$DEFAULT_DB_NAME}"

mkdir -p "$STREAMLIT_DIR"
if [[ -f "$SECRETS_FILE" ]]; then
  cp "$SECRETS_FILE" "${SECRETS_FILE}.bak"
fi

cat > "$SECRETS_FILE" <<EOF
DB_HOST = "$ip_address"
DB_PORT = $port_endpoint
DB_USER = "$hw_usr"
DB_PASSWORD = "$hw_pswrd"
DB_NAME = "$db_name"
EOF

echo
echo "Wrote Streamlit secrets to $SECRETS_FILE"
echo "The app reads these keys directly: DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME"
echo "Launch the app from the repo root with: streamlit run nl2sql_app.py"
